export const CHARACTERS = {
    "Mario": "mario",
    "Donkey Kong": "donkey",
    "Link": "link",
    "Samus": "samus",
    "Dark Samus": "samusd",
    "Yoshi": "yoshi",
    "Kirby": "kirby",
    "Fox": "fox",
    "Pikachu": "pikachu",
    "Luigi": "luigi",
    "Ness": "ness",
    "Captain Falcon": "captain",
    "Jigglypuff": "purin",
    "Peach": "peach",
    "Daisy": "daisy",
    "Bowser": "koopa",
    "Ice Climbers": "ice_climber",
    "Sheik": "sheik",
    "Zelda": "zelda",
    "Dr Mario": "mariod",
    "Pichu": "pichu",
    "Falco": "falco",
    "Marth": "marth",
    "Lucina": "lucina",
    "Young Link": "younglink",
    "Ganondorf": "ganon",
    "Mewtwo": "mewtwo",
    "Roy": "roy",
    "Chrom": "chrom",
    "Mr Game And Watch": "gamewatch",
    "Meta Knight": "metaknight",
    "Pit": "pit",
    "Dark Pit": "pitb",
    "Zero Suit Samus": "szerosuit",
    "Wario": "wario",
    "Snake": "snake",
    "Ike": "ike",
    "Pokemon Trainer": "ptrainer",
    "Diddy Kong": "diddy",
    "Lucas": "lucas",
    "Sonic": "sonic",
    "King Dedede": "dedede",
    "Olimar": "pikmin",
    "Lucario": "lucario",
    "Rob": "robot",
    "Toon Link": "toonlink",
    "Wolf": "wolf",
    "Villager": "murabito",
    "Mega Man": "rockman",
    "Wii Fit Trainer": "wiifit",
    "Rosalina And Luma": "rosetta",
    "Little Mac": "littlemac",
    "Greninja": "gekkouga",
    "Mii Brawler": "miifighter",
    "Mii Swordfighter": "miiswordsman",
    "Mii Gunner": "miigunner",
    "Palutena": "palutena",
    "Pac Man": "pacman",
    "Robin": "reflet",
    "Shulk": "shulk",
    "Bowser Jr": "koopajr",
    "Duck Hunt": "duckhunt",
    "Ryu": "ryu",
    "Ken": "ken",
    "Cloud": "cloud",
    "Corrin": "kamui",
    "Bayonetta": "bayonetta",
    "Inkling": "inkling",
    "Ridley": "ridley",
    "Simon": "simon",
    "Richter": "richter",
    "King K Rool": "krool",
    "Isabelle": "shizue",
    "Incineroar": "gaogaen",
    "Piranha Plant": "packun",
    "Joker": "jack",
    "Hero": "brave",
    "Banjo-Kazooie": "buddy",
    "Terry": "dolly",
    "Byleth": "master",
    "Min Min": "tantan",
    "Steve": "pickel",
    "Sephiroth": "edge",
    "Random": "random"
}

export const CHARACTER_EYE_HEIGHT_PERCENTAGE = {
    "Mario": 50,
    "Donkey Kong": 34,
    "Link": 52,
    "Samus": 52,
    "Dark Samus": 40,
    "Yoshi": 20,
    "Kirby": 22,
    "Fox": 52,
    "Pikachu": 45,
    "Luigi": 45,
    "Ness": 52,
    "Captain Falcon": 52,
    "Jigglypuff": 50,
    "Peach": 45,
    "Daisy": 50,
    "Bowser": 26,
    "Ice Climbers": 45,
    "Sheik": 45,
    "Zelda": 45,
    "Dr Mario": 42,
    "Pichu": 52,
    "Falco": 50,
    "Marth": 50,
    "Lucina": 46,
    "Young Link": 52,
    "Ganondorf": 45,
    "Mewtwo": 58,
    "Roy": 48,
    "Chrom": 50,
    "Mr Game And Watch": 25,
    "Meta Knight": 56,
    "Pit": 56,
    "Dark Pit": 50,
    "Zero Suit Samus": 46,
    "Wario": 22,
    "Snake": 42,
    "Ike": 44,
    "Pokemon Trainer": 56,
    "Diddy Kong": 30,
    "Lucas": 54,
    "Sonic": 60,
    "King Dedede": 44,
    "Olimar": 32,
    "Lucario": 58,
    "Rob": 50,
    "Toon Link": 60,
    "Wolf": 62,
    "Villager": 54,
    "Mega Man": 64,
    "Wii Fit Trainer": 42,
    "Rosalina And Luma": 50,
    "Little Mac": 48,
    "Greninja": 58,
    "Mii Brawler": 45,
    "Mii Swordfighter": 56,
    "Mii Gunner": 52,
    "Palutena": 48,
    "Pac Man": 14,
    "Robin": 44,
    "Shulk": 44,
    "Bowser Jr": 18,
    "Duck Hunt": 28,
    "Ryu": 38,
    "Ken": 46,
    "Cloud": 42,
    "Corrin": 44,
    "Bayonetta": 44,
    "Inkling": 60,
    "Ridley": 26,
    "Simon": 40,
    "Richter": 34,
    "King K Rool": 20,
    "Isabelle": 42,
    "Incineroar": 48,
    "Piranha Plant": 30,
    "Joker": 50,
    "Hero": 46,
    "Banjo-Kazooie": 56,
    "Terry": 52,
    "Byleth": 52,
    "Min Min": 74,
    "Steve": 42,
    "Sephiroth": 56,
    "Random": 50
}

export const CHARACTERS_GG_TO_BRAACKET = {
	"Mario": "Mario",
	"Donkey Kong": "Donkey Kong",
	"Link": "Link",
	"Samus": "Samus",
	"Dark Samus": "Dark Samus",
	"Yoshi": "Yoshi",
	"Kirby": "Kirby",
	"Fox": "Fox",
	"Pikachu": "Pikachu",
	"Luigi": "Luigi",
	"Ness": "Ness",
	"Captain Falcon": "Captain Falcon",
	"Jigglypuff": "Jigglypuff",
	"Peach": "Peach",
	"Daisy": "Daisy",
	"Bowser": "Bowser",
	"Ice Climbers": "Ice Climbers",
	"Sheik": "Sheik",
	"Zelda": "Zelda",
	"Dr. Mario": "Dr Mario",
	"Pichu": "Pichu",
	"Falco": "Falco",
	"Marth": "Marth",
	"Lucina": "Lucina",
	"Young Link": "Young Link",
	"Ganondorf": "Ganondorf",
	"Mewtwo": "Mewtwo",
	"Roy": "Roy",
	"Chrom": "Chrom",
	"Mr. Game & Watch": "Mr Game And Watch",
	"Meta Knight": "Meta Knight",
	"Pit": "Pit",
	"Dark Pit": "Dark Pit",
	"Zero Suit Samus": "Zero Suit Samus",
	"Wario": "Wario",
	"Snake": "Snake",
	"Ike": "Ike",
	"Pokemon Trainer": "Pokemon Trainer",
	"Diddy Kong": "Diddy Kong",
	"Lucas": "Lucas",
	"Sonic": "Sonic",
	"King Dedede": "King Dedede",
	"Olimar": "Olimar",
	"Lucario": "Lucario",
	"R.O.B.": "Rob",
	"Toon Link": "Toon Link",
	"Wolf": "Wolf",
	"Villager": "Villager",
	"Mega Man": "Mega Man",
	"Wii Fit Trainer": "Wii Fit Trainer",
	"Rosalina": "Rosalina And Luma",
	"Little Mac": "Little Mac",
	"Greninja": "Greninja",
	"Mii Brawler": "Mii Brawler",
	"Mii Swordfighter": "Mii Swordfighter",
	"Mii Gunner": "Mii Gunner",
	"Palutena": "Palutena",
	"Pac-Man": "Pac Man",
	"Robin": "Robin",
	"Shulk": "Shulk",
	"Bowser Jr.": "Bowser Jr",
	"Duck Hunt": "Duck Hunt",
	"Ryu": "Ryu",
	"Ken": "Ken",
	"Cloud": "Cloud",
	"Corrin": "Corrin",
	"Bayonetta": "Bayonetta",
	"Inkling": "Inkling",
	"Ridley": "Ridley",
	"Simon Belmont": "Simon",
	"Richter": "Richter",
	"King K. Rool": "King K Rool",
	"Isabelle": "Isabelle",
	"Incineroar": "Incineroar",
	"Piranha Plant": "Piranha Plant",
	"Joker": "Joker",
	"Hero": "Hero",
	"Banjo-Kazooie": "Banjo-Kazooie",
	"Terry": "Terry",
	"Byleth": "Byleth",
	"Min Min": "Min Min",
    "Steve": "Steve",
    "Sephiroth": "Sephiroth"
}

export default CHARACTERS