const CHARACTER_TO_CODENAME = {
    "ssbu":{
        "Mario": "mario",
        "Donkey Kong": "donkey",
        "Link": "link",
        "Samus": "samus",
        "Dark Samus": "samusd",
        "Yoshi": "yoshi",
        "Kirby": "kirby",
        "Fox": "fox",
        "Pikachu": "pikachu",
        "Luigi": "luigi",
        "Ness": "ness",
        "Captain Falcon": "captain",
        "Jigglypuff": "purin",
        "Peach": "peach",
        "Daisy": "daisy",
        "Bowser": "koopa",
        "Ice Climbers": "ice_climber",
        "Sheik": "sheik",
        "Zelda": "zelda",
        "Dr Mario": "mariod",
        "Pichu": "pichu",
        "Falco": "falco",
        "Marth": "marth",
        "Lucina": "lucina",
        "Young Link": "younglink",
        "Ganondorf": "ganon",
        "Mewtwo": "mewtwo",
        "Roy": "roy",
        "Chrom": "chrom",
        "Mr Game And Watch": "gamewatch",
        "Meta Knight": "metaknight",
        "Pit": "pit",
        "Dark Pit": "pitb",
        "Zero Suit Samus": "szerosuit",
        "Wario": "wario",
        "Snake": "snake",
        "Ike": "ike",
        "Pokemon Trainer": "ptrainer",
        "Diddy Kong": "diddy",
        "Lucas": "lucas",
        "Sonic": "sonic",
        "King Dedede": "dedede",
        "Olimar": "pikmin",
        "Lucario": "lucario",
        "Rob": "robot",
        "Toon Link": "toonlink",
        "Wolf": "wolf",
        "Villager": "murabito",
        "Mega Man": "rockman",
        "Wii Fit Trainer": "wiifit",
        "Rosalina And Luma": "rosetta",
        "Little Mac": "littlemac",
        "Greninja": "gekkouga",
        "Mii Brawler": "miifighter",
        "Mii Swordfighter": "miiswordsman",
        "Mii Gunner": "miigunner",
        "Palutena": "palutena",
        "Pac Man": "pacman",
        "Robin": "reflet",
        "Shulk": "shulk",
        "Bowser Jr": "koopajr",
        "Duck Hunt": "duckhunt",
        "Ryu": "ryu",
        "Ken": "ken",
        "Cloud": "cloud",
        "Corrin": "kamui",
        "Bayonetta": "bayonetta",
        "Inkling": "inkling",
        "Ridley": "ridley",
        "Simon": "simon",
        "Richter": "richter",
        "King K Rool": "krool",
        "Isabelle": "shizue",
        "Incineroar": "gaogaen",
        "Piranha Plant": "packun",
        "Joker": "jack",
        "Hero": "brave",
        "Banjo-Kazooie": "buddy",
        "Terry": "dolly",
        "Byleth": "master",
        "Min Min": "tantan",
        "Steve": "pickel",
        "Sephiroth": "edge",
        "Random": "random"
    }
}

export function GetCharacterCodename(game, char){
    if(CHARACTER_TO_CODENAME[game]){
        if(CHARACTER_TO_CODENAME[game][char]){
            return CHARACTER_TO_CODENAME[game][char];
        }
    }
    if(char == null){char = ""};
    return char.replace(/ /g, "_").replace(/\./g, "").toLowerCase();
}

const CHARACTER_EYE_HEIGHT_PERCENTAGE = {
    "ssbu": {
        "Mario": {0: 50},
        "Donkey Kong": {0: 34}, 
        "Link": {0: 52},
        "Samus": {0: 52},
        "Dark Samus": {0: 40},
        "Yoshi": {0: 20},
        "Kirby": {0: 22},
        "Fox": {0: 52},
        "Pikachu": {0: 45},
        "Luigi": {0: 45},
        "Ness": {0: 52},
        "Captain Falcon": {0: 52},
        "Jigglypuff": {0: 50},
        "Peach": {0: 45},
        "Daisy": {0: 50},
        "Bowser": {0: 26},
        "Ice Climbers": {0: 45},
        "Sheik": {0: 45},
        "Zelda": {0: 45},
        "Dr Mario": {0: 42},
        "Pichu": {0: 52},
        "Falco": {0: 50},
        "Marth": {0: 50},
        "Lucina": {0: 46},
        "Young Link": {0: 52},
        "Ganondorf": {0: 45},
        "Mewtwo": {0: 58},
        "Roy": {0: 48},
        "Chrom": {0: 50},
        "Mr Game And Watch": {0: 25},
        "Meta Knight": {0: 56},
        "Pit": {0: 56},
        "Dark Pit": {0: 50},
        "Zero Suit Samus": {0: 46},
        "Wario": {0: 22},
        "Snake": {0: 42},
        "Ike": {0: 44},
        "Pokemon Trainer": {0: 56},
        "Diddy Kong": {0: 30},
        "Lucas": {0: 54},
        "Sonic": {0: 60},
        "King Dedede": {0: 44},
        "Olimar": {0: 32},
        "Lucario": {0: 58},
        "Rob": {0: 50},
        "Toon Link": {0: 60},
        "Wolf": {0: 62},
        "Villager": {0: 54},
        "Mega Man": {0: 64},
        "Wii Fit Trainer": {0: 42},
        "Rosalina And Luma": {0: 50},
        "Little Mac": {0: 48},
        "Greninja": {0: 58},
        "Mii Brawler": {0: 45},
        "Mii Swordfighter": {0: 56},
        "Mii Gunner": {0: 52},
        "Palutena": {0: 48},
        "Pac Man": {0: 14},
        "Robin": {0: 44},
        "Shulk": {0: 44},
        "Bowser Jr": {0: 18},
        "Duck Hunt": {0: 28},
        "Ryu": {0: 38},
        "Ken": {0: 46},
        "Cloud": {0: 42},
        "Corrin": {0: 44},
        "Bayonetta": {0: 44},
        "Inkling": {0: 60},
        "Ridley": {0: 26},
        "Simon": {0: 40},
        "Richter": {0: 34},
        "King K Rool": {0: 20},
        "Isabelle": {0: 42},
        "Incineroar": {0: 48},
        "Piranha Plant": {0: 30},
        "Joker": {0: 50},
        "Hero": {0: 46, 1: 65, 2: 56, 3: 50, 4: 46, 5: 65, 6: 56, 7: 50},
        "Banjo-Kazooie": {0: 56},
        "Terry": {0: 52},
        "Byleth": {0: 52},
        "Min Min": {0: 74},
        "Steve": {0: 42},
        "Sephiroth": {0: 56},
        "Random": {0: 50}
    },
    "sfv": {
        "ALL": {0: 30},
        "Ryu": {0: 30},
        "Akuma": {0: 30}
    },
    "ssbm": {
        "ALL": {0: 30},
        "Jigglypuff": {0: 80},
        "Captain Falcon": {0: 16},
        "Peach": {0: 50},
        "Ganondorf": {0: 20}
    }

}

export function GetCharacterEyeHeight(game, char, skins={}){
    if(CHARACTER_EYE_HEIGHT_PERCENTAGE[game]){
        if(CHARACTER_EYE_HEIGHT_PERCENTAGE[game][char]){
            if(CHARACTER_EYE_HEIGHT_PERCENTAGE[game][char][skins[char]]){
                return CHARACTER_EYE_HEIGHT_PERCENTAGE[char][skins[char]];
            }
        }
        if(CHARACTER_EYE_HEIGHT_PERCENTAGE[game][char]){
            return CHARACTER_EYE_HEIGHT_PERCENTAGE[game][char][0];
        }
        if(CHARACTER_EYE_HEIGHT_PERCENTAGE[game]["ALL"]){
            return CHARACTER_EYE_HEIGHT_PERCENTAGE[game]["ALL"][0];
        }
    }
    else return 50;
}

export const CHARACTERS_GG_TO_BRAACKET = {
	"Mario": "Mario",
	"Donkey Kong": "Donkey Kong",
	"Link": "Link",
	"Samus": "Samus",
	"Dark Samus": "Dark Samus",
	"Yoshi": "Yoshi",
	"Kirby": "Kirby",
	"Fox": "Fox",
	"Pikachu": "Pikachu",
	"Luigi": "Luigi",
	"Ness": "Ness",
	"Captain Falcon": "Captain Falcon",
	"Jigglypuff": "Jigglypuff",
	"Peach": "Peach",
	"Daisy": "Daisy",
	"Bowser": "Bowser",
	"Ice Climbers": "Ice Climbers",
	"Sheik": "Sheik",
	"Zelda": "Zelda",
	"Dr. Mario": "Dr Mario",
	"Pichu": "Pichu",
	"Falco": "Falco",
	"Marth": "Marth",
	"Lucina": "Lucina",
	"Young Link": "Young Link",
	"Ganondorf": "Ganondorf",
	"Mewtwo": "Mewtwo",
	"Roy": "Roy",
	"Chrom": "Chrom",
	"Mr. Game & Watch": "Mr Game And Watch",
	"Meta Knight": "Meta Knight",
	"Pit": "Pit",
	"Dark Pit": "Dark Pit",
	"Zero Suit Samus": "Zero Suit Samus",
	"Wario": "Wario",
	"Snake": "Snake",
	"Ike": "Ike",
	"Pokemon Trainer": "Pokemon Trainer",
	"Diddy Kong": "Diddy Kong",
	"Lucas": "Lucas",
	"Sonic": "Sonic",
	"King Dedede": "King Dedede",
	"Olimar": "Olimar",
	"Lucario": "Lucario",
	"R.O.B.": "Rob",
	"Toon Link": "Toon Link",
	"Wolf": "Wolf",
	"Villager": "Villager",
	"Mega Man": "Mega Man",
	"Wii Fit Trainer": "Wii Fit Trainer",
	"Rosalina": "Rosalina And Luma",
	"Little Mac": "Little Mac",
	"Greninja": "Greninja",
	"Mii Brawler": "Mii Brawler",
	"Mii Swordfighter": "Mii Swordfighter",
	"Mii Gunner": "Mii Gunner",
	"Palutena": "Palutena",
	"Pac-Man": "Pac Man",
	"Robin": "Robin",
	"Shulk": "Shulk",
	"Bowser Jr.": "Bowser Jr",
	"Duck Hunt": "Duck Hunt",
	"Ryu": "Ryu",
	"Ken": "Ken",
	"Cloud": "Cloud",
	"Corrin": "Corrin",
	"Bayonetta": "Bayonetta",
	"Inkling": "Inkling",
	"Ridley": "Ridley",
	"Simon Belmont": "Simon",
	"Richter": "Richter",
	"King K. Rool": "King K Rool",
	"Isabelle": "Isabelle",
	"Incineroar": "Incineroar",
	"Piranha Plant": "Piranha Plant",
	"Joker": "Joker",
	"Hero": "Hero",
	"Banjo-Kazooie": "Banjo-Kazooie",
	"Terry": "Terry",
	"Byleth": "Byleth",
	"Min Min": "Min Min",
    "Steve": "Steve",
    "Sephiroth": "Sephiroth"
}